sudo: false

language: node_js

before_install:
  - npm install -g npm@latest
  - sudo apt-get -qq update
  - sudo apt-get install -y g++ m4 libtool automake                 # build tools
  - sudo apt-get install -y libxext-dev libxtst-dev libxkbfile-dev  # spellchecker headers

node_js:
  - 4
  - 5
  - 6
  - 7
  - stable

script:
  - pwd   # run no-op to prevent failure from no tests
